### ISSUE TITLE
Kindly add all remaining countries to countries.geo.js

### ISSUE THREAD

**Issue by kul1010** [yanivam/react-svg-worldmap#122]
Hi,
Kindly add all remaining countries to countries.geo.js and update this file. Also Geo Polygon coordinates showing wrong for India Map.
Kindly Refer for correct India Map https://www.mapmyindia.com/api/advanced-maps/WebSDK-LiveDemo/mapmyindia_addgeojson_polygon.

I want updated countries.geo.js.

Kindly do he needful

**Comment by kul1010** [comment]
Hi,
Any update.
If you are busy then kindly let me know where i can get pending countries Geo polygon data which are given in \node_modules\react-svg-worldmap\dist\countries.geo.js

**Comment by Josh-Cena** [comment]
Please send a PR directly if you know how to update it, that's the point of open-source :)

AFAIK, we directly downloaded the data from an open data registry (I can't remember which one). If you want to make any corrections, feel free to.

**Comment by jahirfiquitiva** [comment]
@Josh-Cena @yanivam

How can I import the data in `countries.geo.ts`? I am getting this error in a NextJS app

![Shot 2022-06-14 at 15 09 19@2x](https://user-images.githubusercontent.com/10360816/173679928-1b905ff7-915f-42aa-b44b-9dcdcd3e3040.png)

My code is:
```typescript
import countries from 'react-svg-worldmap/dist/countries.geo';

const data: Data = countries.features.map((country) => {
  return { country: country.I, value: 0 };
});
```

**Comment by yanivam** [comment]
Hey @kul1010,
Thank you for the request. Our map is an open source map from NASA and does not have all of the ISO codes on Wikipedia intentionally because we did not want to make this map political in any way. We simply wanted an easy to import map component but we did not want to get into any disputes as to our data and so we chose an open source map that already exists. If you wish to add missing countries to the geo.js file, you can file a PR in which you make the changes locally and we will review whether or not they are controversial. We intentionally tried to stay away from any political conflicts that arise from this issue and we are also working on a feature to let users make their own maps but have not had the time to put that together quite yet. Thank you for your patience as it has been an incredibly busy time for me personally.
Yams

**Comment by MaxwellKeeble** [comment]
Hi, referencing #137 - can you clarify which map this pulls from, from NASA? e.g. a URL to the source. This doesn't appear to be included anywhere, in the readme or the license, so it'd be helpful regardless to document this.

(I think it's optimistic to avoid politics when it comes to country borders, but it'd be good to provide options to choose from at the very least).

**Comment by yanivam** [comment]
Hey, I have clarified in the README
