### ISSUE TITLE
How to inject HTML in tooltip

### ISSUE THREAD

**Issue by kul1010** [yanivam/react-svg-worldmap#124]
How to inject HTML in tooltip in [react-svg-worldmap](https://github.com/yanivam/react-svg-worldmap)

**Comment by Josh-Cena** [comment]
This needs to be filed in https://github.com/yanivam/react-path-tooltip instead.

@yanivam Mind giving me push access to that repo as well? My refactor is currently stalled by some API design in that package.

**Comment by yanivam** [comment]
Our original intention with the tooltip was to keep it as a static, unclickable value rather than something like an embed link to keep things simple (the intention if the map is a simple react component that you can add to a project easily). I am marking this as a feature request as well but I have not decided whether we should add it or not yet. I will discuss with @Josh-Cena and get back to you with our decision.
Thanks for the request,
Yams

**Comment by yanivam** [comment]
Hey, I have decided that this is not in the scope of this project
