### ISSUE TITLE
Can't resolve d3-geo

### ISSUE THREAD

**Issue by Aichnerc** [yanivam/react-svg-worldmap#38]
**Describe the bug**
`Module not found: Can't resolve 'd3-geo' in '...\node_modules\react-svg-worldmap\dist'`

**To Reproduce**
1. `npm i react-svg-worldmap`
2. `npm start` or if not in scripts use `react-scripts start`
3. See error

**Expected behavior**
The module should be found and actually work.

**Desktop (please complete the following information):**
  - OS: Win 10 Pro
  - Browser: Google Chrome
  - Version: 83

**Comment by yanivam** [comment]
Hey Aichnerc,

Thanks so much for using the map! I have been looking into the problem and believe that it is an issue with dependencies. Essentially, I did not make d3-geo a peer dependency and, therefore, you were not prompted to install it in the same way as react.

In the next version of the map, I will make it a peer dependency so that you are prompted to install it as well as change the README to accommodate for this bug. I am working on adding a feature and will push the change in with the new feature.

Thanks again for using my map and taking the time out to write this bug report, it really means a lot to a student that is trying to learn all that I can during the summer. Having people like you looking and trying out these components is really exciting!

For now, I say try just doing `npm i d3-geo` and see if it works but it might require some finagling.

Hope you have a good day,
Yams

**Comment by yanivam** [comment]
I have added d3-geo to the dependencies and so the bug should now be fixed, let me know if you have any more issues and thanks for your patience.

**Comment by Aichnerc** [comment]
Seems to work now!
