### ISSUE TITLE
Remove console.log from source code

### ISSUE THREAD

**Issue by prionkor** [yanivam/react-svg-worldmap#46]
https://github.com/yanivam/react-svg-worldmap/blob/master/src/WorldMap.tsx#L105

**Comment by yanivam** [comment]
Thanks so much for catching that! Missed it while reviewing my code. It should be fixed in the latest version that I just released addressing that issue (1.0.27). Feel free to let me know if you have any features you would like for me to try to tackle and have issues with. I will close this issue for now but thank you again for giving it a look, the more the merrier!
