### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by omer921** [yanivam/react-svg-worldmap#67]
Does this work with react native?

**Comment by yanivam** [comment]
Hey Omer!
While I have not tested this out myself, if you want, you can make a branch off of dev and create an example project underneath the examples folder and name it react-native-example to test it out and I can add it to the next update of the map. I can also test it out myself locally so as to see if it works before then. Thanks so much for checking this map out and for your question.
Let me know what you think!
Yams

**Comment by omer921** [comment]
Hi!

I tried plugging it into my react native iOS app and got some weird errors. I am a react native newbie so any help would be greatly appreciated. This map is supper cool I would love to use it in my app.

Thanks!


>

**Comment by yanivam** [comment]
Hey,
 
I just read a little bit about it here: 

https://medium.com/@aakashns/sharing-components-between-react-and-react-native-f6ce3713658a

It seems like it doesn’t work for React Native right away but with a little nudge and finagle it might. I’ve decided to try it out tonight and let you know how it goes. I will keep you posted. Thanks so much for the kind words about the map, it’s really exciting to see people using it!

Thanks,
Yams

**Comment by omer921** [comment]
Thank you please do! Would be immensely useful for React Native as there is no simple repo for maps.

**Comment by yanivam** [comment]
After extensively trying to make an example for react native and trying to get it to work, I have come to the conclusion that this is not possible yet because React and react native differ in their UI components. Essentially, React for the web uses React-DOM for styling and components which react native does not. I will hopefully create a new project soon to address this difference and share code from this project to create a react native version. Thank you for the suggestion and for thinking about ways I can improve on this project. I really appreciate the kind words and the interest. I will update you on the status of that project once I get it up and running but for now I will close this issue so that we can start a new dialogue when the new project is created.
