### ISSUE TITLE
[BUG] The dist folder misses index.js file

### ISSUE THREAD

**Issue by devbucket** [yanivam/react-svg-worldmap#69]
When trying to import `import { WorldMap } from 'react-svg-worldmap'` inside of a non-typescript project, the bundler fails, because the `dist` folder inside the npm package does not have an `index.js` file included.

**To Reproduce**
1. install the module inside a non-typescript project
2. try to transpile the code.
3. the bundler should moan on you because it can't resolve the module.

**Comment by yanivam** [comment]
Good catch. Going to read about this because my dist folder has an index.d.ts file rather than an index.js file and so I have to look at why that is significant. Will let you know when I figure it out.

**Comment by yanivam** [comment]
Hey @devbucket,

After additional research, I am considering creating two packages for the worldmap: one optimized for typecript (the currrent worldmap) and one for the javascript users (compiled with the commonjs directive). This will keep the package size smaller for each consumer and therefore be more optimal than doing it all in one package. Would this approach work for your need? (I would include a link for javascript users in the README for the javascript package and vice versus).

Let me know,
Yams

**Comment by devbucket** [comment]
Hey @yanivam,

Thanks a lot for looking into this. Yes, this would be perfect!
Thank you very much!

**Comment by devbucket** [comment]
Hey @yanivam,
Can you tell me when I can try out the new package? I am still having issues with the current one since our project is not written in TypeScript.

**Comment by yanivam** [comment]
Hey @devbucket,
I am going to add this to my backlog and keep you posted. I currently have been getting a lot of requests about features to implement/bugs and am also working two jobs while finishing my last semester of college so it is kind of hard to do all at once. After reading about this a little bit more I kind of understand the issue. I think the best way to communicate would be to email me rather than do it through chat so I can keep you posted. My email is: yanivam123@gmail.com.
Thanks,
Yams
